### ISSUE TITLE
jitify2_preprocess require -lpthread in linkage stage for safety

### ISSUE THREAD

**Issue by JunHuohuo** [NVIDIA/jitify#114]
In jitify, the app uses dlopen() to load libnvrtc.so, not dynamical link in compilation.  It could cause a hidden trouble about pthread and stdc++ libraries.  
This story has a description in detail :  
[https://stackoverflow.com/questions/51209268/using-stdthread-in-a-library-loaded-with-dlopen-leads-to-a-sigsev](https://stackoverflow.com/questions/51209268/using-stdthread-in-a-library-loaded-with-dlopen-leads-to-a-sigsev)

It will cause the pthread_create function call into nullptr ptr in somewhere, because libnvrtc.so depends pthread but jitify2_preprocess does not.

for safety, the jitify2_preprocess could depend on pthread in linkage stage. for example:

./CMakeLists.txt:84:  target_link_libraries(jitify2_preprocess PRIVATE ${CMAKE_DL_LIBS})
=> ./CMakeLists.txt:84:  target_link_libraries(jitify2_preprocess PRIVATE ${CMAKE_DL_LIBS} pthread)

**Comment by maddyscientist** [comment]
closed by #115
