### ISSUE TITLE
Why doesn't JITIFY support CUDA 10?

### ISSUE THREAD

**Issue by bzigon** [NVIDIA/jitify#19]
Hello, I've been chasing a jitify bug for 2 days. I am using VC++ 2017, CUDA 10 and Win7/64.
I was seeing weird things happen in release mode that didnt happen in debug mode.
Then I went back to the jitify home page and saw that it only works on cuda 7, 8 and 9.
Why doesn't it work on CUDA 10? What is the issue?
--Bob

**Comment by maddyscientist** [comment]
Closing this issue, since it isn't an issue.
