### ISSUE TITLE
Kernels running progressively slower

### ISSUE THREAD

**Issue by Simoncl** [NVIDIA/jitify#20]
Hi.
I have a simple kernel that's run in a draw loop. I have noticed it takes longer and longer to execute? (my frames per second drops)  In my program if I comment out the kernel launch it does not get progressively slower and maintains a steady frame rate.  The kernel is compiled once and then uses the cache.  The only bit of my code I need to comment out to maintain a steady frame rate is the following.

static_cast<jitify::Program*>(m_program)->kernel("my_kernel")
		.instantiate(count, jitify::reflection::type_of(*indata))
		.configure(grid, block)
		.launch(indata, mag);

So if I run my program in the first 1000 frames I get around 314fps by frame 3427 i'm down to 121fps

Have you guys tried running a jitify  kernel like this effectively calling a kernel in loop many thousands of times?

I noticed in KernelInstantiation new is called if I'm running the same kernel again and again can the cache handle this. I have a feeling I'm doing this wrong? 
Any help appreciated. 
Cheers

Simon

**Comment by maddyscientist** [comment]
Closing since not an issue.
