### ISSUE TITLE
create_module build error when using JITIFY_PRINT_LOG

### ISSUE THREAD

**Issue by mondus** [NVIDIA/jitify#50]
```JITIFY_PRINT_LOG``` is incorrectly used in ```create_module``. It should instead use ```JITIFY_PRINT_LINKER_LOG``` else there is a build failure due to ```_error_log``` not existing.

**Comment by mondus** [comment]
pull request #51 makes the one line change

**Comment by benbarsdell** [comment]
Thanks for the heads up, I actually caught this in #49, though I didn't realise it caused a build error.
