### ISSUE TITLE
Integration with Occupancy Calculator

### ISSUE THREAD

**Issue by DavidPoliakoff** [NVIDIA/jitify#7]
Hey Folks,

I've been working on using Jitify, before getting to the request just wanted to say the software has been really excellent.

I know NVIDIA has an Occupancy Calculator, there's a bit of code which uses it [here](https://github.com/LLNL/RAJA/pull/433/files#diff-3d4b36a45be7d3abe14eafb862e21375R292), the code is a little dense, but essentially you can get the ideal occupancy for a kernel. I believe your kernels are represented in your KernelInstantiations [here](https://github.com/NVIDIA/jitify/blob/master/jitify.hpp#L1782), and we interface with that most closely [here](https://github.com/NVIDIA/jitify/blob/master/jitify.hpp#L1865). I'd like to be able to call something like `myKernelInstantation.configureViaCalculator()` and have the calculator handle that logic and return a KernelLauncher

Any opposition? If not, would it be easier for you to accept a pull request or write code yourselves?

Thanks again, really excited to get JIT capabilities.

**Comment by DavidPoliakoff** [comment]
Just a followup: NVIDIA has two Occupancy Calculators, one is the Excel Spreadsheet, which is wonderful but not what I'm talking about. I'm talking about [these](http://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__HIGHLEVEL.html#group__CUDART__HIGHLEVEL_1gee5334618ed4bb0871e4559a77643fc1) runtime functions

**Comment by benbarsdell** [comment]
Thanks for the suggestion! Does #8 look OK?

**Comment by DavidPoliakoff** [comment]
That's perfect, and thanks so much, a three hour turnaround time is extremely impressive and helpful
