### ISSUE TITLE
Author email address(es) unavailable

### ISSUE THREAD

**Issue by eyalroz** [NVIDIA/jitify#83]
There's no obvious way - except opening an issue - to get in touch with the authors of jitify. README.md doesn't have mailto links, nor do the two main contributors' GitHub profiles.

**Comment by maddyscientist** [comment]
Hi @eyalroz.

Thanks for reporting this.  https://github.com/NVIDIA/jitify/commit/5f8f0a1e62bf0289e83d1188ec6b150d27016a6e fixes this.

Closing this bug.
