### ISSUE TITLE
GTC Talk link is dead

### ISSUE THREAD

**Issue by mondus** [NVIDIA/jitify#84]
The GTC portal no longer has a link to the jitify GTC talk (404). This is a shame as its a great intro to the tool.

**Comment by maddyscientist** [comment]
Thanks @mondus.  I'm looking into this.  Regardless if we can resurrect this or not, I'll get the slides from our talk online.

**Comment by eyalroz** [comment]
@maddyscientist : So, the link in the README has not been replaced and is still dead.
