### ISSUE TITLE
Does jitify supports CUDA 11.x???

### ISSUE THREAD

**Issue by FdyCN** [NVIDIA/jitify#91]
i really appreciate for y'all to provide this nice header.  it's really helpful.   but it seems to stop updating for a long time ?  so does it support latest CUDA version?? thanks!

**Comment by Robadob** [comment]
We actively use it as part of FLAMEGPU2 (https://github.com/FLAMEGPU/FLAMEGPU2).

We've been using it with CUDA version from 10.2-11.4, without any problems related to changes within CUDA.

**Comment by FdyCN** [comment]
> 
@Robadob 
Thank you for ur reply. I still have one more question.   
is it possible to overload operator "+-*/" in the ".cuh" header like those in example_headers,  and using these overloading in the headers who are included in the kernel string??  seems hard to approach, cause kernel string has specified extern "C", i try to remove extern "C", but nvrtc will return error.  is there any possibility to overloader operators??  thanks a lot!

**Comment by Robadob** [comment]
I'm not sure what example you're referring to, but operator overloading works.

We've used operator overloads in some of our own code ([e.g.](https://github.com/FLAMEGPU/FLAMEGPU2/blob/ae59d08c1bf779da5eede759d50bf2f10fbc56a7/include/flamegpu/runtime/utility/DeviceMacroProperty.cuh#L106)) and it's also heavily use by [GLM](https://github.com/g-truc/glm) a header library we sometime use within NVRTC compiled kernels.

The main challenge with NVRTC compilation is that host code and system headers are not supported. So you have to be very careful in what the compiler sees. Jitify only helps in this manner by providing an incomplete set of drop-in system header replacements that might be wanted in device code. There can still be some effort required to get existing headers to be supported by NVRTC/Jitify.

**Comment by FdyCN** [comment]
> 

@Robadob thanks for ur reply. i tried to overload operator in the a header which will be included in my kernel source. And it works, that's nice. i will keep following this header and your job ,it's really helpful. thank you again.
