### ISSUE TITLE
Memory leak within nvrtcCompileProgram()

### ISSUE THREAD

**Issue by Robadob** [NVIDIA/jitify#92]
*This isn't a bug within Jitify, but likely of interest to Jitify users.*

Right before Christmas we were running a large complicated benchmark, which results in ~500 RTC compilations on HPC. We noticed that executing this, the memory footprint grew to over 10GB. A re-execution, where most compilations were skipped and instead loaded from the disc cache we create then used significantly less memory.

Playing with `valgrind` identified a leak within `nvrtcCreateProgram()`.

Further testing on Windows suggests the leak is actually caused by `nvrtcCompileProgram()`. Larger source inputs appear to create a larger leak, but the leak size isn't a 1:1 mapping.

The leak appears present in atleast CUDAs 11.2, 11.4 and 11.5 on both Linux and Windows.

Our original issue: https://github.com/FLAMEGPU/FLAMEGPU2/issues/756
A short explain of the valgrind run: https://gist.github.com/ptheywood/ca81e19dd8fe79e75ae3269014389009
Trivial NVRTC Loop that produces small memory increases: https://gist.github.com/Robadob/77ef11e6e8fdd72d6431218da4ff7da4
NV Bug Report Link: https://developer.nvidia.com/nvidia_bug/3488772

**Comment by benbarsdell** [comment]
We believe this is actually a Jitify issue. Can you check if #93 fixes it?

**Comment by Robadob** [comment]
Thanks

I've just tested this with a subset of the benchmark that we originally discovered the issue, it works out to 64 Jitify compilations.

Pre-fix memory peak: ~3848MB
Post-fix memory peak: ~408MB

So it does appear to have fixed the issue!

Sorry for the misdirection in my original report, in my haste I missed that it was possible for the call to `nvrtcDestroyProgram()` to be skipped within Jitify.
